name: Build CI/CD

on:
  push:
    branches:
      - main

jobs:
  compile:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Compile binary
        run: go build -o myapp
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download
      
      - name: Run tests
        run: go test ./...
  build:
      runs-on: ubuntu-latest
      permissions:
              contents: write
              packages: write
      needs: compile
      if: success()

      steps:
           - name: Checkout code
             uses: actions/checkout@v4
           - name: Setup Go
             uses: actions/setup-go@v5
             with:
                     go-version: '1.22'
           - name: Log in GHCR
             uses: docker/login-action@v3
             with:
                  registry: ghcr.io
                  username: ${{ github.actor }}             # GitHub username (actor triggering the workflow)
                  password: ${{ secrets.GITHUB_TOKEN }}     # Automatically provided GitHub token
           - name: Build Docker Image
             run: docker build -t ghcr.io/${{ github.repository }}:latest .
           - name: Push Docker Image
             run: docker push ghcr.io/${{ github.repository }}:latest
